default_topics = [
    "natural language processing",
    "neural networks",
    "text processing",
    "python nltk",
    "python stemming",
    "python scraping",
    "deep learning",
    "lemmatize",
    "natural language",
    "python tokenizer",
    "tokenizer",
    "text classification",
    "probability concepts",
    "tensor flow" "pytorch",
    "python numpy",
    "python pandas",
    "beautiful soup python",
    "machine learning cost function",
    "pytorch",
    "generative model",
    "GAN model",
    "VAE model",
    "backpropagation",
    "serverless",
    "cloud native",
    "kafka",
    "cockroachdb",
    "kafka streams",
    "KSQL",
    "druid database",
    "microservices",
    "chaos engineering",
    "data mining",
    "big data",
    "data mining",
    "microservices monitoring",
    "grafana",
    "golang",
    "MongoDB",
    "Cassandra",
    "high availability",
    "kubernetes",
    "k8s helm",
    "k8s rancher",
    "golang testing",
    "http benchmark",
    "ddos",
    "rabbitmq",
    "redis",
    "event sourcing",
    "microservices saga",
    "cqrs",
]

topics_categories = {
    "natural language processing": "NLP",
    "neural networks": "ML",
    "text processing": "NLP",
    "python nltk": "NLP",
    "python stemming": "NLP",
    "python scraping": "NLP",
    "deep learning": "ML",
    "lemmatize": "NLP",
    "natural language": "NLP",
    "python tokenizer": "NLP",
    "tokenizer": "NLP",
    "text classification": "NLP",
    "probability concepts": "NLP",
    "tensor flow": "ML",
    "pytorch": "ML",
    "python numpy": "ML",
    "python pandas": "ML",
    "beautiful soup python": "NLP",
    "machine learning cost function": "ML",
    "generative model": "ML",
    "GAN model": "ML",
    "VAE model": "ML",
    "backpropagation": "ML",
    "serverless": "Cloud",
    "cloud native": "Cloud",
    "kafka": "Events",
    "cockroachdb": "Data",
    "kafka streams": "Events",
    "KSQL": "Events",
    "druid database": "Events",
    "microservices": "Cloud",
    "chaos engineering": "Cloud",
    "data mining": "Data",
    "big data": "Data",
    "data mining": "Data",
    "microservices monitoring": "Cloud",
    "grafana": "Cloud",
    "golang": "Golang",
    "MongoDB": "Data",
    "Cassandra": "Data",
    "high availability": "Cloud",
    "kubernetes": "Cloud",
    "k8s helm": "Cloud",
    "k8s rancher": "Cloud",
    "golang testing": "Golang",
    "http benchmark": "Cloud",
    "ddos": "Cloud",
    "rabbitmq": "Events",
    "redis": "Data",
    "event sourcing": "Events",
    "microservices saga": "Events",
    "cqrs": "Events",
}
